# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1920e7806355659e1c5d64aa6936a46d8d3e8ca6d91766eb1e4854b0deb05f0628db54d0118e641c7275b6ace41ad7ea72bdae3621ffb51a967de5e9b78fee9

test:
  secret_key_base: d8951717294d4dc2352f5f44dc05df89ff1ff9b4be68ec0f05f7238e50872c0ed3a34af4b74c096e15953f4ecb8fcc42bf9984118df21ef7a24789687e964d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
