# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e3f4291e700498e6b551668f5bcf535ad8e88e7849b8ca9404ade3631716ff87821ac7f5b6015848890756298ed52e6818d66790eef48d6f0bebd1417267d2c

test:
  secret_key_base: 0cf4e83f7227221f0f4168bdd10311d761578835b47ebaa174d3a14b19a59845938a8d4e627bc395f966e4d95ffd7d649c1306bcd24c22fd40f80b7d467707c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
